# azure-pipelines-build.yml
trigger:
- main  # Runs on code push

pool:
  name: Default  # Your self-hosted agent pool

variables:
  BACKEND_IP: "10.0.3.4"
  BACKEND_USER: "azureuser"
  APP_DIR: "/django-app/chatapp-modified-ubuntu-22.04"
  ARTIFACT_DIR: "/tmp/build-artifacts"  # On backend VM

steps:
- script: |
    ssh ${BACKEND_USER}@${BACKEND_IP} "
      # Clean and setup
      rm -rf ${ARTIFACT_DIR} &&
      mkdir -p ${ARTIFACT_DIR} &&
      
      # Clone fresh code
      git clone https://github.com/sg2263/chatapp-modified-ubuntu-22.04.git ${ARTIFACT_DIR}/src &&
      
      # Build steps
      cd ${ARTIFACT_DIR}/src &&
      python -m venv venv &&
      source venv/bin/activate &&
      pip install -r requirements.txt &&
      python fundoo/manage.py makemigrations &&
      python fundoo/manage.py migrate &&
      
      # Freeze dependencies and package
      pip freeze > requirements.lock &&
      tar -czf ${ARTIFACT_DIR}/django-app.tar.gz -C ${ARTIFACT_DIR}/src ."
  displayName: 'Build + Migrate + Package'

- script: |
    # Download artifact from backend VM to Azure DevOps
    scp ${BACKEND_USER}@${BACKEND_IP}:${ARTIFACT_DIR}/django-app.tar.gz $(Build.ArtifactStagingDirectory)/
  displayName: 'Fetch artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/django-app.tar.gz'
    ArtifactName: 'django-app'
  displayName: 'Publish artifact'