trigger:
- main

pool:
  name: default

variables:
  BACKEND_IP: "10.0.0.6"
  BACKEND_USER: "azureuser"
  APP_DIR: "/docker-chatapp"

stages:
- stage: DeployStage
  displayName: 'Deploy Containers'
  jobs:
  - job: dockerDeploy
    steps:
    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} "
          cd ${APP_DIR} &&
          docker-compose down &&
         # docker-compose pull &&
          docker-compose up -d"
      displayName: 'Deploy Dockerized ChatApp'
