trigger:
- main

pool:
  name: default

variables:
  BACKEND_IP: "10.0.0.6"
  BACKEND_USER: "azureuser"
  APP_DIR: "/docker-chatapp"

stages:
- stage: DeployStage
  displayName: 'Deploy Containers'
  jobs:
  - job: dockerDeploy
    steps:
    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} "
          cd ${APP_DIR} &&
          sudo rm -rf backend/chatapp-modified-ubuntu-22.04 &&
          sudo git clone https://github.com/sg2263/chatapp-modified-ubuntu-22.04.git backend/chatapp-modified-ubuntu-22.04 &&
          sudo docker compose down &&
          sudo docker compose up -d  "
          
         # docker-compose pull &&
          
      displayName: 'Deploy Dockerized ChatApp'
