trigger:
- main

pool:
  name: Default

variables:
  BACKEND_IP: "10.0.3.4"
  BACKEND_USER: "azureuser"
  APP_DIR: "/django-app/chatapp-modified-ubuntu-22.04"
  TMP_DIR: "/tmp/az-chatapp"

stages:
- stage: FetchCodeStage
  displayName: 'Clone and Prepare Code'
  jobs:
  - job: clone
    steps:
    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} "
          rm -rf ${TMP_DIR} &&
          mkdir -p ${TMP_DIR} &&
          git clone https://github.com/sg2263/chatapp-modified-ubuntu-22.04.git ${TMP_DIR} &&
          cd ${TMP_DIR} &&
          git pull origin main"
      displayName: 'Clone and update repository'

- stage: BuildStage
  displayName: 'Build and Deploy'
  jobs:
    - job: build
      steps:
      - script: |
          ssh ${BACKEND_USER}@${BACKEND_IP} "
            cp ${TMP_DIR}/requirements.txt ${APP_DIR}/ &&
            sudo rm -rf ${APP_DIR}/fundoo &&
            sudo mv ${TMP_DIR}/fundoo ${APP_DIR}/"
        displayName: 'Copy application files'

      - script: |
          ssh ${BACKEND_USER}@${BACKEND_IP} "
            cd ${APP_DIR} &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            python fundoo/manage.py makemigrations &&
            python fundoo/manage.py migrate"
        displayName: 'Install dependencies and run migrations'

      - script: |
          ssh ${BACKEND_USER}@${BACKEND_IP} "sudo systemctl restart django"
        displayName: 'Restart Django service'