trigger:
- main

pool:
  name: Default

variables:
  BACKEND_IP: "10.0.3.4"
  BACKEND_USER: "azureuser"
  APP_DIR: "/django-app/chatapp-modified-ubuntu-22.04"
  TMP_DIR: "/tmp/az-chatapp"

stages:

- stage: FetchCode
  displayName: 'Clone & Prepare Code'
  jobs:
  - job: clone
    steps:
    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} << 'EOF'
        rm -rf ${TMP_DIR}
        mkdir -p ${TMP_DIR}
        git clone https://github.com/sg2263/chatapp-modified-ubuntu-22.04.git ${TMP_DIR}
        cd ${TMP_DIR}
        git pull origin main
        EOF
      displayName: 'Clone and update repository'

    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} << 'EOF'
        cp ${TMP_DIR}/requirements.txt ${APP_DIR}/
        sudo rm -rf ${APP_DIR}/fundoo
        sudo mv ${TMP_DIR}/fundoo ${APP_DIR}/
        EOF
      displayName: 'Changes migrated'


- stage: BuildBackend
  displayName: 'Build and Migrate'
  jobs:
  - job: build
    steps:
    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} << 'EOF'
        cd ${APP_DIR}
        source venv/bin/activate
        pip install -r requirements.txt
        sudo venv/bin/python3 fundoo/manage.py makemigrations
        sudo venv/bin/python3 fundoo/manage.py migrate
        EOF
      displayName: 'Run Backend Build'

- stage: Restart
  displayName: 'Restart Django Service'
  jobs:
  - job: restart
    steps:
    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} "sudo systemctl restart django"
      displayName: 'Restart Django Service'
