# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: |
    ssh azureuser@10.0.3.4 "
      # Remove existing directory if it exists
      rm -rf /tmp/az-chatapp &&
      # Create fresh directory
      mkdir -p /tmp/az-chatapp &&
      # Clone repository (replace with your actual repo URL)
      git clone https://github.com/sg2263/chatapp-modified-ubuntu-22.04.git /tmp/az-chatapp &&
      # Navigate to directory
      cd /tmp/az-chatapp &&
      # Pull latest changes
      git pull origin main"
  displayName: 'Clone and update repository'

