trigger:
- main

pool:
  name: default

variables:
  BACKEND_IP: "10.0.0.6"
  BACKEND_USER: "azureuser"
  APP_DIR: "/docker-chatapp"

stages:
- stage: DeployStage
  displayName: 'Deploy Containers'
  jobs:
  - job: dockerDeploy
    steps:
    - script: |
        ssh ${BACKEND_USER}@${BACKEND_IP} "
          cd ${APP_DIR} &&
          sudo docker-compose down &&
          rm -rf /backend/chatapp-modified-ubuntu-22.04 &&
          git clone https://github.com/sg2263/chatapp-modified-ubuntu-22.04.git /backend/chatapp-modified-ubuntu-22.04 &&
          
         # docker-compose pull &&
          sudo docker-compose up -d"
      displayName: 'Deploy Dockerized ChatApp'
