trigger:
- main

pool:
  name: Default

variables:
  BACKEND_IP: "10.0.3.4"
  BACKEND_USER: "azureuser"
  APP_DIR: "/django-app/chatapp-modified-ubuntu-22.04"
  TMP_DIR: "/tmp/az-chatapp"

steps:
- script: |
    ssh ${BACKEND_USER}@${BACKEND_IP} "
      # Remove existing directory if it exists
      rm -rf ${TMP_DIR} &&
      # Create fresh directory
      mkdir -p ${TMP_DIR} &&
      # Clone repository
      git clone https://github.com/sg2263/chatapp-modified-ubuntu-22.04.git ${TMP_DIR} &&
      # Navigate to directory
      cd ${TMP_DIR} &&
      # Pull latest changes
      git pull origin main"
  displayName: 'Clone and update repository'

- script: |
    ssh ${BACKEND_USER}@${BACKEND_IP} "
      # Copy requirements file
      cp ${TMP_DIR}/requirements.txt ${APP_DIR}/ &&
      # Remove old directory if exists
      sudo rm -rf ${APP_DIR}/fundoo &&
      # Move new files
      sudo mv ${TMP_DIR}/fundoo ${APP_DIR}/"
  displayName: 'Changes migrated'

- script: |
    ssh ${BACKEND_USER}@${BACKEND_IP} "
    cd ${APP_DIR} &&
    source venv/bin/activate &&
    pip install -r requirements.txt &&
    sudo venv/bin/python3 fundoo/manage.py makemigrations &&
    sudo venv/bin/python3 fundoo/manage.py migrate "
  displayName: 'Build Successful'

- script: |
    ssh ${BACKEND_USER}@${BACKEND_IP} "
      sudo systemctl restart django 
  displayName: 'Restart Server'